version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_IMAGE: node:22.11.0-alpine
    image: reflection-diary:latest
    container_name: reflection-diary-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://localhost:3000}
      - ORIGIN=${PUBLIC_BASE_URL:-http://localhost:3000}
      - SESSION_SECRET=${SESSION_SECRET:-change_this_in_production}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-false}
      - DATA_DIR=/home/node/app/data
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - reflection_diary_data:/home/node/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  reflection_diary_data:
    name: reflection_diary_data
