version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_BASE_URL=http://localhost:5000
      - SESSION_SECRET=${SESSION_SECRET:-change_this_in_production}
      - SESSION_COOKIE_SECURE=false
      # Uncomment the following line if using OpenAI API
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # For persistent data storage (optional)
      - reflection_diary_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  reflection_diary_data: